name: 'TestAgent'

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo ${{ secrets.C8YCERT }} > piCert.pem
        echo ${{ secrets.C8YKEY }} > piCertKey.pem
        cat piCert.pem
        cat piCertKey.pem
        
