name: 'TestAgent'

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: dev
    - name: Setup Python
      uses: actions/setup-python@v2.2.1
    - name: Install python deps
      shell: bash
      run: python3 -m pip install -r ./requirements.txt
    - name: Create files
      shell: bash
      env:
        CERT: ${{ secrets.C8YCERT }}
        KEY: ${{ secrets.C8YKEY }}
      run: |
        ls -la /etc/ssl/certs/ca-certificates.crt
        echo $CERT | wc -l
        echo $CERT
        echo $CERT | base64 --decode > piCert.pem
        echo $KEY  | base64 --decode > piCertKey.pem
        cat piCertKey.pem
        echo "[device]
        name = Pi
        host = mqtt.eu-latest.cumulocity.com
        port = 8883
        tls = true
        cert_auth = true
        client_cert = piCert.pem
        client_key = piCertKey.pem
        cacert = /etc/ssl/certs/ca-certificates.crt
        operations = c8y_Restart,c8y_Message,c8y_Configuration,c8y_SendConfiguration,c8y_RemoteAccessConnect,c8y_SoftwareList
        subscribe = s/ds,s/dc/pi,s/e,s/dt
        devicetype = c8y_Pi
        sendinterval = 5
        requiredinterval = 10
        loglevel = DEBUG
        reboot = 0
        config_update = 0
        bootstrap_pwd = Fhdt1bb1f
        serial=0000000070596700" > pi.properties
    - name: Run Agent
      run: python piAgent.py

        
        
